import React, { useState } from 'react';
import { uploadScriptResults } from '../services/api';
import './ResultsUpload.css';

const ResultsUpload = ({ projectId, onUploadComplete }) => {
  const [selectedFiles, setSelectedFiles] = useState([]);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState(null);
  const [uploadProgress, setUploadProgress] = useState(null);

  // Don't render if projectId is missing
  if (!projectId) {
    return (
      <div className="results-upload-container">
        <div className="alert alert-warning">
          Project ID not available. Please complete the assessment first.
        </div>
      </div>
    );
  }

  const handleFileSelect = (event) => {
    const files = Array.from(event.target.files);
    setSelectedFiles(prevFiles => [...prevFiles, ...files]);
    setError(null);
  };

  const removeFile = (index) => {
    setSelectedFiles(prevFiles => prevFiles.filter((_, i) => i !== index));
  };

  const formatFileSize = (bytes) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
  };

  const handleUpload = async () => {
    if (selectedFiles.length === 0) {
      setError('Please select at least one file to upload');
      return;
    }

    setUploading(true);
    setError(null);
    setUploadProgress(`Uploading ${selectedFiles.length} file(s)...`);

    try {
      const result = await uploadScriptResults(projectId, selectedFiles);
      setUploadProgress(`Successfully uploaded ${result.files.length} file(s)`);
      
      setTimeout(() => {
        setSelectedFiles([]);
        setUploadProgress(null);
        if (onUploadComplete) {
          onUploadComplete(result);
        }
      }, 2000);
    } catch (err) {
      console.error('Upload error:', err);
      console.error('Error details:', err.response?.data);
      
      // Extract error message
      let errorMessage = 'Failed to upload files. Please try again.';
      if (err.response?.data?.detail) {
        const detail = err.response.data.detail;
        errorMessage = typeof detail === 'string' 
          ? detail 
          : (Array.isArray(detail) 
            ? detail.map(e => e.msg || JSON.stringify(e)).join(', ')
            : JSON.stringify(detail));
      } else if (err.message) {
        errorMessage = err.message;
      }
      
      setError(errorMessage);
      setUploadProgress(null);
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="results-upload-container">
      <h3>📤 Upload Script Results</h3>
      <p className="upload-description">
        Upload the output files generated by running the assessment scripts on your servers.
      </p>

      <div className="file-input-wrapper">
        <label htmlFor="file-upload" className="file-input-label">
          <span className="file-icon">📁</span>
          Choose Files
        </label>
        <input
          id="file-upload"
          type="file"
          multiple
          onChange={handleFileSelect}
          accept=".csv,.txt,.json,.xml,.xlsx,.xls,.log,.pdf,.html"
          disabled={uploading}
        />
      </div>

      {selectedFiles.length > 0 && (
        <div className="selected-files">
          <h4>Selected Files ({selectedFiles.length})</h4>
          <ul className="file-list">
            {selectedFiles.map((file, index) => (
              <li key={index} className="file-item">
                <div className="file-info">
                  <span className="file-name">{file.name}</span>
                  <span className="file-size">{formatFileSize(file.size)}</span>
                </div>
                <button
                  type="button"
                  onClick={() => removeFile(index)}
                  className="remove-btn"
                  disabled={uploading}
                >
                  ✕
                </button>
              </li>
            ))}
          </ul>

          <button
            onClick={handleUpload}
            disabled={uploading}
            className="upload-btn"
          >
            {uploading ? '⏳ Uploading...' : `📤 Upload ${selectedFiles.length} File(s)`}
          </button>
        </div>
      )}

      {uploadProgress && (
        <div className="upload-progress success">
          {uploadProgress}
        </div>
      )}

      {error && (
        <div className="upload-error">
          {error}
        </div>
      )}

      <div className="allowed-formats">
        <strong>Allowed formats:</strong> CSV, TXT, JSON, XML, XLSX, XLS, LOG, PDF, HTML
        <br />
        <strong>Max file size:</strong> 50MB per file
      </div>
    </div>
  );
};

export default ResultsUpload;
